# -*- encoding : utf-8 -*-
FactoryGirl.define do
  factory :user do
    sequence(:first_name) {|n| "Max_#{n}" }
    last_name 'Mustermann'
    password '12345678'
    profile_image_id 'profile_picture_default.png'

    after(:create) do |user, evaluator|
      if evaluator.primary_email.nil?
        create(:user_email, user: user)
      else
        create(:user_email, user: user, address: evaluator.primary_email)
      end
    end
    after(:stub) do |user, evaluator|
      if evaluator.primary_email.nil?
        user.emails = [build_stubbed(:user_email, user: user)]
      else
        user.emails = [build_stubbed(:user_email, user: user, address: evaluator.primary_email)]
      end
      allow(user).to receive(:primary_email).and_return(user.emails.first.address)
    end
  end

  factory :fullUser, class: User do
    first_name 'Maximus'
    last_name 'Mustermannnus'
    password '12345678'
    password_autogenerated false
    gender 'Titan'
    profile_image_id 'profile_picture_default.png'
    about_me 'Sieh mich an und erstarre!'

    after(:create) do |user|
      create(:user_email, user: user)
    end
    after(:stub) do |user|
      user.emails = [build_stubbed(:user_email, user: user)]
      allow(user).to receive(:primary_email).and_return(user.emails.first.address)
    end
  end

  factory :OmniAuthUser, class: User do
    sequence(:first_name) {|n| "Max_#{n}" }
    last_name 'Mustermann'
    password Devise.friendly_token[0, 20]
    password_autogenerated true
    profile_image_id 'profile_picture_default.png'

    after(:create) do |user|
      identity = create(:user_identity, user: user)
      create(:user_email, user: user, address: "autogenerated@#{identity.provider_user_id.downcase}-#{identity.omniauth_provider.downcase}.com")
    end
    after(:stub) do |user|
      identity = create(:user_identity, user: user)
      user.emails = [build_stubbed(:user_email, user: user, address: "autogenerated@#{identity.provider_user_id.downcase}-#{identity.omniauth_provider.downcase}.com")]
      allow(user).to receive(:primary_email).and_return(user.emails.first.address)
    end
  end
end
