require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'vendor/**/*'
    - 'db/schema.rb'

Rails:
  Enabled: true

Style/Encoding:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Style/RaiseArgs:
  EnforcedStyle: compact

Style/Documentation:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Style/MixinUsage:
  Exclude:
    - 'bin/*'

Layout/CaseIndentation:
  EnforcedStyle: end
  SupportedStyles:
    - case
    - end
  IndentOneStep: true

Style/Semicolon:
  Exclude:
    - '**/*_spec.rb'

Style/RescueModifier:
  Exclude:
    - '**/*_spec.rb'

Style/RegexpLiteral:
  AllowInnerSlashes: true

Style/ClassAndModuleChildren:
  EnforcedStyle: nested
  Exclude:
   - 'config/application.rb'

Style/CommentedKeyword:
  Enabled: false

Naming/FileName:
  Exclude:
  - 'Gemfile'

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/SpaceInsideBlockBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space
  SpaceBeforeBlockParameters: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Layout/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 30

Metrics/PerceivedComplexity:
  Max: 35

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/ReversibleMigration:
  Enabled: false

Rails/CreateTableWithTimestamps:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
   - 'spec/views/**/*'

RSpec/ExampleLength:
  Enabled: false

RSpec/ExpectActual:
 Exclude:
  - 'spec/routing/**/*'

RSpec/NestedGroups:
  Enabled: false

#######################
# Should be refactored
#######################

RSpec/AnyInstance:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/LetSetup:
  Enabled: false
