class MergeFirstNameAndLastNameToFullName < ActiveRecord::Migration[5.2]
  module FirstAndLastNameMethods
    def first_name_autogenerated?
      autogenerated = false
      UserIdentity.where(user: self).find_each do |identity|
        autogenerated = true if "autogenerated@#{identity.provider_user_id}-#{identity.omniauth_provider}.com".downcase.match(first_name.downcase).present?
      end
      autogenerated
    end

    def last_name_autogenerated?
      autogenerated = false
      UserIdentity.where(user: self).find_each do |identity|
        autogenerated = true if "autogenerated@#{identity.provider_user_id}-#{identity.omniauth_provider}.com".downcase.match(last_name.downcase).present?
      end
      autogenerated
    end
  end

  def change
    add_column :users, :full_name, :string

    User.send(:include, FirstAndLastNameMethods)

    User.all.each do |user|
      first_name = user.first_name
      last_name = user.last_name

      if user.first_name_autogenerated? and user.last_name_autogenerated?
        # Both are equal, so take any for the full_name
        user.full_name = user.first_name
      elsif user.first_name_autogenerated? and !user.last_name_autogenerated?
        # Last name is not autogenerated, so take that
        user.full_name = user.last_name
      elsif !user.first_name_autogenerated? and user.last_name_autogenerated?
        # First name is not autogenerated, so take that
        user.full_name = user.first_name
      else
        user.full_name = "#{user.first_name} #{user.last_name}"
      end
      user.save!
    end

    remove_column :users, :first_name
    remove_column :users, :last_name
  end
end

