require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe CertificatesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Certificate. As you add validations to Certificate, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CertificatesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  let(:user) {FactoryGirl.create(:user)}

  before(:each) do
    sign_in user
  end
  
  describe "GET index" do
    it "assigns all certificates as @certificates" do
      certificate = Certificate.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:certificates)).to eq([certificate])
    end
  end

  describe "GET show" do
    it "assigns the requested certificate as @certificate" do
      certificate = Certificate.create! valid_attributes
      get :show, {:id => certificate.to_param}, valid_session
      expect(assigns(:certificate)).to eq(certificate)
    end
  end

  describe "GET new" do
    it "assigns a new certificate as @certificate" do
      get :new, {}, valid_session
      expect(assigns(:certificate)).to be_a_new(Certificate)
    end
  end

  describe "GET edit" do
    it "assigns the requested certificate as @certificate" do
      certificate = Certificate.create! valid_attributes
      get :edit, {:id => certificate.to_param}, valid_session
      expect(assigns(:certificate)).to eq(certificate)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Certificate" do
        expect {
          post :create, {:certificate => valid_attributes}, valid_session
        }.to change(Certificate, :count).by(1)
      end

      it "assigns a newly created certificate as @certificate" do
        post :create, {:certificate => valid_attributes}, valid_session
        expect(assigns(:certificate)).to be_a(Certificate)
        expect(assigns(:certificate)).to be_persisted
      end

      it "redirects to the created certificate" do
        post :create, {:certificate => valid_attributes}, valid_session
        expect(response).to redirect_to(Certificate.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved certificate as @certificate" do
        post :create, {:certificate => invalid_attributes}, valid_session
        expect(assigns(:certificate)).to be_a_new(Certificate)
      end

      it "re-renders the 'new' template" do
        post :create, {:certificate => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested certificate" do
        certificate = Certificate.create! valid_attributes
        put :update, {:id => certificate.to_param, :certificate => new_attributes}, valid_session
        certificate.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested certificate as @certificate" do
        certificate = Certificate.create! valid_attributes
        put :update, {:id => certificate.to_param, :certificate => valid_attributes}, valid_session
        expect(assigns(:certificate)).to eq(certificate)
      end

      it "redirects to the certificate" do
        certificate = Certificate.create! valid_attributes
        put :update, {:id => certificate.to_param, :certificate => valid_attributes}, valid_session
        expect(response).to redirect_to(certificate)
      end
    end

    describe "with invalid params" do
      it "assigns the certificate as @certificate" do
        certificate = Certificate.create! valid_attributes
        put :update, {:id => certificate.to_param, :certificate => invalid_attributes}, valid_session
        expect(assigns(:certificate)).to eq(certificate)
      end

      it "re-renders the 'edit' template" do
        certificate = Certificate.create! valid_attributes
        put :update, {:id => certificate.to_param, :certificate => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested certificate" do
      certificate = Certificate.create! valid_attributes
      expect {
        delete :destroy, {:id => certificate.to_param}, valid_session
      }.to change(Certificate, :count).by(-1)
    end

    it "redirects to the certificates list" do
      certificate = Certificate.create! valid_attributes
      delete :destroy, {:id => certificate.to_param}, valid_session
      expect(response).to redirect_to(certificates_url)
    end
  end

end
