# -*- encoding : utf-8 -*-
require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ProgressesController, type: :controller do
  # This should return the minimal set of attributes required to create a valid
  # Progress. As you add validations to Progress, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ProgressesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  let(:user) { FactoryGirl.create(:user) }

  before(:each) do
    sign_in user
  end

  describe 'GET index' do
    it 'assigns all progresses as @progresses' do
      progress = Progress.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:progresses)).to eq([progress])
    end
  end

  describe 'GET show' do
    it 'assigns the requested progress as @progress' do
      progress = Progress.create! valid_attributes
      get :show, {id: progress.to_param}, valid_session
      expect(assigns(:progress)).to eq(progress)
    end
  end

  describe 'GET new' do
    it 'assigns a new progress as @progress' do
      get :new, {}, valid_session
      expect(assigns(:progress)).to be_a_new(Progress)
    end
  end

  describe 'GET edit' do
    it 'assigns the requested progress as @progress' do
      progress = Progress.create! valid_attributes
      get :edit, {id: progress.to_param}, valid_session
      expect(assigns(:progress)).to eq(progress)
    end
  end

  describe 'POST create' do
    describe 'with valid params' do
      it 'creates a new Progress' do
        expect do
          post :create, {progress: valid_attributes}, valid_session
        end.to change(Progress, :count).by(1)
      end

      it 'assigns a newly created progress as @progress' do
        post :create, {progress: valid_attributes}, valid_session
        expect(assigns(:progress)).to be_a(Progress)
        expect(assigns(:progress)).to be_persisted
      end

      it 'redirects to the created progress' do
        post :create, {progress: valid_attributes}, valid_session
        expect(response).to redirect_to(Progress.last)
      end
    end

    describe 'with invalid params' do
      it 'assigns a newly created but unsaved progress as @progress' do
        post :create, {progress: invalid_attributes}, valid_session
        expect(assigns(:progress)).to be_a_new(Progress)
      end

      it "re-renders the 'new' template" do
        post :create, {progress: invalid_attributes}, valid_session
        expect(response).to render_template('new')
      end
    end
  end

  describe 'PUT update' do
    describe 'with valid params' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested progress' do
        progress = Progress.create! valid_attributes
        put :update, {id: progress.to_param, progress: new_attributes}, valid_session
        progress.reload
        skip('Add assertions for updated state')
      end

      it 'assigns the requested progress as @progress' do
        progress = Progress.create! valid_attributes
        put :update, {id: progress.to_param, progress: valid_attributes}, valid_session
        expect(assigns(:progress)).to eq(progress)
      end

      it 'redirects to the progress' do
        progress = Progress.create! valid_attributes
        put :update, {id: progress.to_param, progress: valid_attributes}, valid_session
        expect(response).to redirect_to(progress)
      end
    end

    describe 'with invalid params' do
      it 'assigns the progress as @progress' do
        progress = Progress.create! valid_attributes
        put :update, {id: progress.to_param, progress: invalid_attributes}, valid_session
        expect(assigns(:progress)).to eq(progress)
      end

      it "re-renders the 'edit' template" do
        progress = Progress.create! valid_attributes
        put :update, {id: progress.to_param, progress: invalid_attributes}, valid_session
        expect(response).to render_template('edit')
      end
    end
  end

  describe 'DELETE destroy' do
    it 'destroys the requested progress' do
      progress = Progress.create! valid_attributes
      expect do
        delete :destroy, {id: progress.to_param}, valid_session
      end.to change(Progress, :count).by(-1)
    end

    it 'redirects to the progresses list' do
      progress = Progress.create! valid_attributes
      delete :destroy, {id: progress.to_param}, valid_session
      expect(response).to redirect_to(progresses_url)
    end
  end
end
