# -*- encoding : utf-8 -*-
require 'devise_helper'

module Users
  class RegistrationsController < Devise::RegistrationsController
    def new
      super
    end

    def create
      flash['error'] ||= []
      exception = ''
      full_user_params = sign_up_params
      full_user_params[:profile_image_id] = 'profile_picture_default.png'
      build_resource(full_user_params)
      begin
        resource.save
      rescue ActiveRecord::RecordInvalid => error
        exception += error.to_s
      end

      yield resource if block_given?
      if resource.persisted? && user_params.key?(:terms_and_conditions_confirmation) && exception.blank?
        if resource.active_for_authentication?
          set_flash_message :notice, :signed_up if is_flashing_format?
          sign_up(resource_name, resource)
          respond_with resource, location: after_sign_up_path_for(resource)
        else
          set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_flashing_format?
          expire_data_after_sign_in!
          respond_with resource, location: after_inactive_sign_up_path_for(resource)
        end
      else
        session_infos = {}
        session_infos[:first_name] = sign_up_params[:first_name]
        session_infos[:last_name] = sign_up_params[:last_name]
        session_infos[:primary_email] = sign_up_params[:primary_email]
        session[:resource] = session_infos
        begin
          resource.destroy
          UserEmail.destroy_all(user_id: nil)
        rescue ActiveRecord::RecordInvalid => error
          exception += error.to_s
        end
        resource.errors.each do |key, value|
          flash['error'] << "#{t('users.sign_in_up.' + key.to_s)} #{value}"
        end
        redirect_to new_user_registration_path
      end

      unless user_params.key?(:terms_and_conditions_confirmation)
        flash['error'] << t('flash.error.sign_up.terms_and_conditions_failure')
      end

      return unless exception.present?
      if exception.to_s.include?('Address is invalid')
        flash['error'] << t('devise.registrations.email.invalid')
      elsif exception.to_s.include?('Address has already been taken.')
        flash['error'] << t('devise.registrations.email.taken')
      end
    end

    # GET/PATCH /users/finish_signup
    def finish_signup
      self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)

      return unless request.patch? && params[:user] && warden.user.password_autogenerated
      flash['error'] = []

      unless user_params.key?(:terms_and_conditions_confirmation)
        flash['error'] << t('flash.error.sign_up.terms_and_conditions_failure')
        # return
      end
      update(dashboard_path, finish_signup_path)
    end

    def update(redirection_success = "#{user_settings_path(current_user.id)}?subsite=account",
               redirection_failure = "#{user_settings_path(current_user.id)}?subsite=account")
      flash['error'] ||= []
      exception = ''
      self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)
      prev_unconfirmed_email = resource.unconfirmed_email if resource.respond_to?(:unconfirmed_email)

      begin
        resource_updated = update_resource(resource, account_update_params)
      rescue ActiveRecord::RecordInvalid => error
        exception += error.to_s
      end

      yield resource if block_given?
      if resource_updated && exception.blank? && flash['error'].blank?
        if is_flashing_format?
          if update_needs_confirmation?(resource, prev_unconfirmed_email)
            flash_key = :update_needs_confirmation
          else
            flash_key = :updated
          end
          set_flash_message :notice, flash_key
        end
        sign_in resource_name, resource, bypass: true
        redirect_to redirection_success, notice: t('flash.notice.users.successfully_updated')
      else
        session_infos = {}
        session_infos[:primary_email] = update_params[:primary_email]
        session_infos[:primary_email] = resource.primary_email unless session_infos[:primary_email].present? && UserEmail.find_by(user: resource).is_autogenerated?
        session_infos[:terms_and_conditions] = user_params.key?(:terms_and_conditions_confirmation) ? true : false
        session[:resource] = session_infos
        resource.errors.each do |key, value|
          flash['error'] << "#{t('users.sign_in_up.' + key.to_s)} #{value}"
        end
        if exception.present? && exception.to_s.include?('Address is invalid')
          flash['error'] << t('devise.registrations.email.invalid')
        elsif exception.present? && exception.to_s.include?('Address has already been taken.')
          flash['error'] << t('devise.registrations.email.taken')
        end
        redirect_to redirection_failure
      end
    end

    def update_resource(resource, params)
      if !resource.password_autogenerated
        super
      else
        resource.update(params)
        resource.password_autogenerated = false
        resource.save!
      end
    end

    def destroy
      if resource.destroy
        Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)
        set_flash_message :notice, :destroyed if is_flashing_format?
        yield resource if block_given?
        respond_with_navigational(resource) { redirect_to after_sign_out_path_for(resource_name) }
      else
        flash['error'] ||= []
        flash['error'] << "#{t('users.settings.still_admin_in_group_error')}"
        redirect_to "#{user_settings_path(current_user.id)}?subsite=account"
      end
    end

    protected

    def after_sign_up_path_for(resource)
      after_sign_in_path_for(resource)
    end

    def after_update_path_for(resource)
      after_sign_in_path_for(resource)
    end

    private

    def sign_up_params
      params.require(:user).permit(:first_name, :last_name, :primary_email, :password, :password_confirmation)
    end

    def user_params
      params.permit(:terms_and_conditions_confirmation)
    end

    def update_params
      params.require(:user).permit(:primary_email, :password, :password_confirmation, :terms_and_conditions_confirmation)
    end

    def add_resource
      @resource = session[:resource]
    end
  end
end
